# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8z3e9JqzaXpNwc4mTF6SboLuqB8tfyk

# Import các thư viện cần thiết
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ActiveLearning-DataMining-Classification-master

from sklearn.neighbors import KNeighborsClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

from sklearn.model_selection import train_test_split
from sklearn import metrics

# https://scikit-learn.org/stable/modules/generated/sklearn.tree.export_text.html#sklearn.tree.export_text

import pandas as pd

#service knn
#price tham số truyền vào từ client
#createdby:dvquan(27/4/2021)
def getData(price):

    """# Lấy dữ liệu của bài toán"""
    df_quan = pd.read_csv('data.csv')

    # xem dữ liệu
    print(df_quan.head(5))


    #input
    X = df_quan[['Price']]

    #nhãn
    y = df_quan['label']

    # chia train, test
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.3,
        stratify=y,
        # https://stackoverflow.com/questions/34842405/parameter-stratify-from-method-train-test-split-scikit-learn
        random_state=0
    )


    # Khởi tạo
    knn_cls = KNeighborsClassifier(
        n_neighbors=3
    )

    # Huấn luyện
    knn_cls.fit(X_train, y_train)

    #thử nghiệm với dữ liệu test
    y_pred = knn_cls.predict(X_test)

    # đánh giá
    report = metrics.classification_report(y_test,y_pred,digits=4)

    print (report)

    # dự đoán với dữ liệu cụ thể
    y_pred = knn_cls.predict([[price]])

    print(y_pred)
    return  y_pred

